### ISSUE TITLE
Resource u'corpora/stopwords' not found.  Please use the NLTK

### ISSUE THREAD

**Issue by lordadamson** [csurfer/gitsuggest#10]
Hi. I cloned the repo and installed it using: `sudo python setup.py install`

```
[adam@macbook ~]$ gitsuggest lordadamson
Password: 
Generating suggestions...
Traceback (most recent call last):
  File "/usr/bin/gitsuggest", line 9, in <module>
    load_entry_point('gitsuggest==0.0.3', 'console_scripts', 'gitsuggest')()
  File "/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/commandline.py", line 57, in main
    repos = list(gs.get_suggested_repositories())
  File "/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/suggest.py", line 66, in get_suggested_repositories
    query = self.__get_query_for_repos(term_count=term_count)
  File "/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/suggest.py", line 250, in __get_query_for_repos
    self.__construct_lda_model()
  File "/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/suggest.py", line 232, in __construct_lda_model
    cleaned_tokens = self.__clean_and_tokenize(repos_of_interest)
  File "/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/suggest.py", line 186, in __clean_and_tokenize
    stopwords = self.__get_words_to_ignore()
  File "/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/suggest.py", line 147, in __get_words_to_ignore
    english_stopwords = nltk.corpus.stopwords.words('english')
  File "/usr/lib/python2.7/site-packages/nltk-3.2.4-py2.7.egg/nltk/corpus/util.py", line 116, in __getattr__
    self.__load()
  File "/usr/lib/python2.7/site-packages/nltk-3.2.4-py2.7.egg/nltk/corpus/util.py", line 81, in __load
    except LookupError: raise e
LookupError: 
**********************************************************************
  Resource u'corpora/stopwords' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/home/adam/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

I can see it's using python2.7 (which is my default python). Should I have installed it using python3 instead?
I don't know what is nltk_data but maybe check if it exists as you install?

**Comment by csurfer** [comment]
Looks like you do not have nltk stopwords corpus. You can download it using this command if you have nltk installed.
`python -c "import nltk; nltk.download('stopwords')"`
