### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/../gitlang/languages.txt

### ISSUE THREAD

**Issue by lordadamson** [csurfer/gitsuggest#12]
```
[adam@macbook antiyoy]$ gitsuggest lordadamson
Password: 
Generating suggestions...
Traceback (most recent call last):
  File "/usr/bin/gitsuggest", line 9, in <module>
    load_entry_point('gitsuggest==0.0.3', 'console_scripts', 'gitsuggest')()
  File "/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/commandline.py", line 57, in main
    repos = list(gs.get_suggested_repositories())
  File "/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/suggest.py", line 66, in get_suggested_repositories
    query = self.__get_query_for_repos(term_count=term_count)
  File "/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/suggest.py", line 250, in __get_query_for_repos
    self.__construct_lda_model()
  File "/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/suggest.py", line 232, in __construct_lda_model
    cleaned_tokens = self.__clean_and_tokenize(repos_of_interest)
  File "/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/suggest.py", line 186, in __clean_and_tokenize
    stopwords = self.__get_words_to_ignore()
  File "/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/suggest.py", line 153, in __get_words_to_ignore
    with open(language_file, 'r') as langauges:
IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/gitsuggest-0.0.3-py2.7.egg/gitsuggest/../gitlang/languages.txt'
```

**Comment by csurfer** [comment]
@lordadamson : There were some rather nasty bugs with respect to static data files which is being used for creation of LDA model. All such bugs have been fixed. Please upgrade the package to latest version and it should work without a hitch.

**Comment by lordadamson** [comment]
alright thank you sir
