### ISSUE TITLE
Resource u'corpora/stopwords' not found

### ISSUE THREAD

**Issue by pikhovkin** [csurfer/gitsuggest#13]
```
Generating suggestions...
Traceback (most recent call last):
  File "/home/username/.envs/gitsuggest/bin/gitsuggest", line 11, in <module>
    sys.exit(main())
  File "/home/username/.envs/gitsuggest/local/lib/python2.7/site-packages/gitsuggest/commandline.py", line 57, in main
    repos = list(gs.get_suggested_repositories())
  File "/home/username/.envs/gitsuggest/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 64, in get_suggested_repositories
    query = self.__get_query_for_repos(term_count=term_count)
  File "/home/username/.envs/gitsuggest/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 230, in __get_query_for_repos
    self.__construct_lda_model()
  File "/home/username/.envs/gitsuggest/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 213, in __construct_lda_model
    cleaned_tokens = self.__clean_and_tokenize(repos_of_interest)
  File "/home/username/.envs/gitsuggest/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 170, in __clean_and_tokenize
    stopwords = self.__get_words_to_ignore()
  File "/home/username/.envs/gitsuggest/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 135, in __get_words_to_ignore
    english_stopwords = nltk.corpus.stopwords.words('english')
  File "/home/username/.envs/gitsuggest/local/lib/python2.7/site-packages/nltk/corpus/util.py", line 116, in __getattr__
    self.__load()
  File "/home/username/.envs/gitsuggest/local/lib/python2.7/site-packages/nltk/corpus/util.py", line 81, in __load
    except LookupError: raise e
LookupError: 
**********************************************************************
  Resource u'corpora/stopwords' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/home/username/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

**Comment by csurfer** [comment]
Please check `Post setup` step of updated README
