### ISSUE TITLE
Raises TypeError From Commandline

### ISSUE THREAD

**Issue by j-chad** [csurfer/gitsuggest#2]
Just ran it with:
```shell
gitsuggest j-chad --password ******
```

```python
Traceback (most recent call last):
  File gitsuggest-script.py", line 11, in <module>
    load_entry_point('gitsuggest==0.0.2', 'console_scripts', 'gitsuggest')()
  File "gitsuggest\commandline.py", line 63, in main
    repos = list(gs.get_suggested_repositories())
  File "gitsuggest\suggest.py", line 64, in get_suggested_repositories
    query = self.__get_query_for_repos(term_count=term_count)
  File "gitsuggest\suggest.py", line 230, in __get_query_for_repos
    self.__construct_lda_model()
  File "gitsuggest\suggest.py", line 204, in __construct_lda_model
    repos_of_interest = self.__get_interests()
  File "gitsuggest\suggest.py", line 118, in __get_interests
    self.__repositories_interested_in.update(cur_user.get_starred())
TypeError: unhashable type: 'Repository'
```

**Comment by csurfer** [comment]
@j-chad : This looks like conflicting releases. Please clean uninstall the gitsuggest using pip. Clear cache and reinstall the latest version `0.0.3`. I have also removed password from command line altogether. Shouldn't have included it in the first place. Current way is better for security.
