### ISSUE TITLE
Traceback when running gitsuggest

### ISSUE THREAD

**Issue by sairahul** [csurfer/gitsuggest#3]
Hi, 

I installed gitsuggest using pip. When i run gitsuggest <username> I am getting following traceback 

I am trying from mac. 

Traceback (most recent call last):
  File "/usr/local/bin/gitsuggest", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/gitsuggest/commandline.py", line 57, in main
    repos = list(gs.get_suggested_repositories())
  File "/usr/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 64, in get_suggested_repositories
    query = self.__get_query_for_repos(term_count=term_count)
  File "/usr/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 230, in __get_query_for_repos
    self.__construct_lda_model()
  File "/usr/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 213, in __construct_lda_model
    cleaned_tokens = self.__clean_and_tokenize(repos_of_interest)
  File "/usr/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 170, in __clean_and_tokenize
    stopwords = self.__get_words_to_ignore()
  File "/usr/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 139, in __get_words_to_ignore
    with open('../gitlang/languages.txt', 'r') as langauges:
IOError: [Errno 2] No such file or directory: '../gitlang/languages.txt'

**Comment by csurfer** [comment]
gitsuggest uses gitlang as a submodule. Have you initialized the submodule properly ?

**Comment by sairahul** [comment]
I ran from command line. 

gitsuggest <myusername> 

initializing is only required when i used as module right ?

**Comment by xiyouMc** [comment]
I have encountered such a problem

**Comment by csurfer** [comment]
@sairahul : There was a bug because of which resources weren't getting packed into the package properly. Its been fixed in the latest version pushed to pypi. Please use latest version now to get it working. Thanks.

**Comment by sairahul** [comment]
Thanks @csurfer . It worked now. We can close the issue.
