### ISSUE TITLE
NLTK resource not found

### ISSUE THREAD

**Issue by CallumHoward** [csurfer/gitsuggest#8]
I get the following when running gitsuggest:

```
Generating suggestions...
Traceback (most recent call last):
  File "/usr/local/bin/gitsuggest", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/gitsuggest/commandline.py", line 57, in main
    repos = list(gs.get_suggested_repositories())
  File "/usr/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 64, in get_suggested_repositories
    query = self.__get_query_for_repos(term_count=term_count)
  File "/usr/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 230, in __get_query_for_repos
    self.__construct_lda_model()
  File "/usr/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 213, in __construct_lda_model
    cleaned_tokens = self.__clean_and_tokenize(repos_of_interest)
  File "/usr/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 170, in __clean_and_tokenize
    stopwords = self.__get_words_to_ignore()
  File "/usr/local/lib/python2.7/site-packages/gitsuggest/suggest.py", line 135, in __get_words_to_ignore
    english_stopwords = nltk.corpus.stopwords.words('english')
  File "/usr/local/lib/python2.7/site-packages/nltk/corpus/util.py", line 116, in __getattr__
    self.__load()
  File "/usr/local/lib/python2.7/site-packages/nltk/corpus/util.py", line 81, in __load
    except LookupError: raise e
LookupError:
**********************************************************************
  Resource u'corpora/stopwords' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/Users/callumhoward/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

On macOS, installed with pip:
```
$ pip show gitsuggest
Name: gitsuggest
Version: 0.0.3
Summary: A tool to suggest github repositories based on the repositories you have shown interest in.
Home-page: https://github.com/csurfer/gitsuggest
Author: Vishwas B Sharma
Author-email: sharma.vishwas88@gmail.com
License: MIT
Location: /usr/local/lib/python2.7/site-packages
Requires: PyGithub, gensim, nltk, pyenchant
```

```
$ python --version
Python 2.7.13
```

**Comment by csurfer** [comment]
Looks like you do not have nltk stopwords corpus. You can download it using this command if you have nltk installed.
`python -c "import nltk; nltk.download('stopwords')"`

**Comment by fire17** [comment]
```
>>> nltk.download('stopwords')
[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1006)>
False
```
actually i need:
```
nltk.download('cmudict')
[nltk_data] Error loading cmudict: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1006)>
False
```
but its the same...
any suggestions?
Thanks!
